AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Serverless rendering of api blueprint files as styled html'

Globals:
  Function:
    Timeout: 15

Resources:
  RenderApibHtmlFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
        Path: "/"
        ManagedPolicyArns:
            - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Sid: "AllowLambdaServiceToAssumeRole"
              Effect: "Allow"
              Action: 
                - "sts:AssumeRole"
              Principal:
                Service: 
                  - "lambda.amazonaws.com"
                  - "edgelambda.amazonaws.com"
  RenderApibHtmlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lib/
      Handler: main.handler
      Runtime: nodejs10.x
      Role: !GetAtt RenderApibHtmlFunctionRole.Arn
  RenderApibHtmlFunctionVersion:
    Type: AWS::Lambda::Version
    Properties: 
      FunctionName: !Ref RenderApibHtmlFunction
  RenderApibHtmlDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: 'true'
        Origins:
          -
            Id: S3-gh-pro-view-render-apib-html
            DomainName: gh-pro-view.s3.amazonaws.com
            OriginPath: /render-apib-html/index.html
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: match-viewer
        DefaultCacheBehavior:
          TargetOriginId: S3-gh-pro-view-render-apib-html
          LambdaFunctionAssociations:
            - 
              EventType: origin-response
              LambdaFunctionARN: !Ref RenderApibHtmlFunctionVersion
          ForwardedValues:
            QueryString: 'false'
            Headers:
              - Origin
              - Referer
              - X-Blueprint
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all

Outputs:
  RenderApibHtmlFunction:
    Description: "Render APIB HTML Lambda Function ARN"
    Value: !Ref RenderApibHtmlFunction
  RenderApibHtmlFunctionVersion: 
    Description: "Render APIB HTML Lambda Function Version"
    Value: !Ref RenderApibHtmlFunctionVersion
  RenderApibHtmlDistribution: 
    Description: Cloudfront Distribution Domain Name
    Value: !GetAtt RenderApibHtmlDistribution.DomainName
  RenderApibHtmlFunctionIamRole:
    Description: "Implicit IAM Role created for Render APIB HTML Function"
    Value: !Ref RenderApibHtmlFunctionRole
