name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: |
        npm ci
    - name: Lint
      run: |
        npm run lint
    - name: Test
      run: |
        npm test -- --ci --coverage
    - name: Build
      run: |
        npm run build
    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm run release
    - name: Report
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        npm run coveralls
