name: Build
on:
  push:
    branches:
      - master
  pull_request_target:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_REF: ${{ github.ref }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install
      run: |
        npm ci --legacy-peer-deps
        pip install aws-sam-cli
    - name: Lint
      run: |
        npm run lint
    - name: Test
      run: |
        npm test -- --ci --coverage
    - name: Build
      if: github.ref != 'refs/heads/master' &&  github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      run: |
        npm run release -- --dry-run --branches=${GITHUB_REF#refs/heads/}
    - name: Release
      if: github.ref == 'refs/heads/master' &&  github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      run: |
        npm run release
    - name: Report
      if:  github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        npm run coveralls
